#!/bin/bash

set -e

mkdir -p build

./shell-test "$@" &> build/shell-test-out.txt || {
    echo "error: shell-test: execution failed"
    echo
    echo "======  full output  ======"
    cat build/shell-test-out.txt
    exit 1
}

diff=$(diff shell-test-ref.txt build/shell-test-out.txt --color=always) || {
    echo "error: shell-test: unexpected output"
    echo
    echo "======  full output  ======"
    cat build/shell-test-out.txt
    echo
    echo "======  diff output  ======"
    echo "$diff"
    exit 2
}
