#!/bin/bash

set -e

source shell-test.config

run() {
    echo -n "\$"
    printf " %q" "$@"
    echo
    "run-$@"
    echo
}

dex-jar() {
    name="$1"
    jar=$name/build/libs/$name.jar
    dex=build/$name.dex.zip
    run d8 --no-desugaring --output $dex $jar
    #run dex2jar --force --output $name-dex2jar.jar $dex
}

run-jar() {
    jar="$1"
    echo "--- run $jar ---"
    run-java -cp $jar test.Main
    echo "--- end $jar ---"
    echo
}

mkdir -p build

dex-jar source
dex-jar patch

run dexpatcher --help
run dexpatcher build/source.dex.zip build/patch.dex.zip --output build/patched.dex\
 --map-source --unmap-output --map mapping.txt\
 --deanon-source --reanon-output --main-plan Anon[_Level] --deanon-patches-alt --no-reanon-errors\
 --decode-source --decode-patches --no-decode-errors\
 --debug "$@"

run sha1sum build/patched.dex

run dex2jar --force --output build/patched-dex2jar.jar build/patched.dex

run-jar source/build/libs/source.jar
run-jar build/patched-dex2jar.jar
